#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


# Unset guardrails
unalias rm
set +o noclobber


# Editor
export EDITOR="$(which atom) --wait"


# zsh completions
fpath=(/usr/local/share/zsh-completions $fpath)


# Python
export PATH=$(python -m site --user-base)/bin:$PATH
